[package]
name = "native-dialog"
version = "0.2.0"
authors = ["balthild <ibalthild@gmail.com>"]
edition = "2018"
description = "A library to display dialogs. Supports GNU/Linux, macOS and Windows."
license = "MIT"
documentation = "https://github.com/balthild/native-dialog-rs/blob/master/README.md"
repository = "https://github.com/balthild/native-dialog-rs"

[dependencies]
thiserror = "1.0.19"

[target.'cfg(target_os = "windows")'.dependencies]
wfd = "0.1.3"
winapi = { version = "0.3", features = ["winuser"] }
kernel32-sys = "0.2.2"

[target.'cfg(target_os = "linux")'.dependencies]
which = "4.0.0"

[target.'cfg(target_os = "macos")'.dependencies]
osascript = "0.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[workspace]
members = [
    "examples/windows_manifest",
]
